language: c
sudo: required
dist: trusty
before_install:
    # maybe add php ppa to provide sufficiant pkg-php-tools
    # - sudo add-apt-repository -y ppa:ondrej/php5
    # update package list
    - sudo apt-get update -qq

install:
    # install build dependencies
    # - sudo apt-get install -qq --no-install-recommends aspell aspell-en binutils bzip2 cdbs debhelper default-jdk diffstat docbook-utils docbook-xml fakeroot file gettext hardening-includes intltool-debian javahelper libapt-pkg-perl libarchive-zip-perl libclass-accessor-perl libclone-perl libdpkg-perl libdigest-sha-perl libemail-valid-perl libfile-basedir-perl libhtml-parser-perl libipc-run-perl liblist-moreutils-perl libparse-debianchangelog-perl libtest-minimumversion-perl libtest-perl-critic-perl libtest-pod-coverage-perl libtest-pod-perl libtest-spelling-perl libtest-strict-perl libtest-synopsis-perl libtext-levenshtein-perl libtext-template-perl libtimedate-perl liburi-perl libyaml-perl man-db node-uglify patchutils perl pkg-php-tools python python-all-dev python-numpy quilt rsync t1utils unzip xz-utils zip
    # install packages needed for mk-build-deps
    - sudo apt-get install -y -qq --no-install-recommends devscripts equivs
    # pull build deps from debian/control
    - yes y | head -n1 | sudo mk-build-deps -ir
    # remove packages needed for mk-build-deps
    - sudo apt-get purge -y -qq equivs
    - sudo apt-get autoremove -y -qq

script:
    # build the debian package
    - debuild -uc -us
#notifications:
#  email: false
